name: after_speclinks_trigger_autohome

on:
  workflow_dispatch:

permissions:
  actions: write   # 他の workflow をトリガーするために必要
  contents: read

jobs:
  trigger-autohome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # （任意）アーティファクト確認
      - name: (optional) Peek spec_links artifact
        run: echo "Peek artifact step (optional)"

      # （任意）HEADログ確認
      - name: (optional) Show head
        run: git log -1 --oneline

      - name: Trigger autohome_from_speclinks workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux
          # ✅ spec_run_id は autohome_from_speclinks.yml 側で定義されていないため削除
          gh workflow run autohome_from_speclinks.yml --ref main
