name: after_speclinks_trigger_autohome

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  trigger-autohome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: (optional) Peek spec_links artifact
        run: echo "skip"

      - name: (optional) Show head
        run: git log -1 --oneline

      - name: Trigger autohome_from_speclinks workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux
          # 422を出していた余計なinputsは渡さない
          gh workflow run autohome_from_speclinks.yml --ref main
