# ★ tiles フォルダの中身を一覧化（任意：見やすいインデックスHTMLを作る）
- name: Build tiles index (optional but useful)
  run: |
    if [ -d tiles ]; then
      {
        echo '<!doctype html><meta charset="utf-8"><title>Tiles Preview</title>'
        echo '<style>body{font-family:system-ui, sans-serif;padding:24px;background:#111;color:#eee}'
        echo '.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:12px}'
        echo 'figure{margin:0;background:#222;padding:8px;border-radius:8px}'
        echo 'figcaption{font-size:12px;margin-top:6px;color:#ccc;word-break:break-all}'
        echo 'img{max-width:100%;height:auto;display:block;border-radius:4px}'
        echo '</style><h1>Autohome tiles</h1><div class="grid">'
        for f in tiles/*.jpg tiles/*.png 2>/dev/null; do
          [ -f "$f" ] || continue
          bn=$(basename "$f")
          echo "<figure><img src=\"$bn\" alt=\"$bn\"><figcaption>$bn</figcaption></figure>"
        done
        echo '</div>'
      } > tiles/index.html
    else
      echo "no tiles/ directory found"
    fi

# ★ 画像タイルをアーティファクトとしてアップロード
- name: Upload tiles as artifact
  if: ${{ always() }}
  uses: actions/upload-artifact@v4
  with:
    name: autohome-tiles-${{ env.TARGET_MONTH }}
    path: |
      tiles/*.jpg
      tiles/*.png
      tiles/index.html
    if-no-files-found: warn
    retention-days: 14

# （任意）CSVも一緒にアーティファクト化しておくと比較が楽
- name: Upload CSVs as artifact (optional)
  if: ${{ always() }}
  uses: actions/upload-artifact@v4
  with:
    name: autohome-csvs-${{ env.TARGET_MONTH }}
    path: |
      data/autohome_raw_${{ env.TARGET_MONTH }}.csv
      data/autohome_rank_${{ env.TARGET_MONTH }}.csv
      data/autohome_dom_${{ env.TARGET_MONTH }}.csv
      data/autohome_dom_rank_${{ env.TARGET_MONTH }}.csv
    if-no-files-found: ignore
    retention-days: 30
