name: autohome_pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "10 1 3 * *"  # monthly at 01:10 UTC on the 3rd

jobs:
  autohome_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright openai pandas beautifulsoup4 requests
          python -m playwright install chromium

      - name: Run stage scripts (ranking)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # 1) ランキング + 画像URL抽出（出力: public/autohome_ranking_with_image_urls.csv）
          python tools/rank_capture_images_and_csv.py
          # 2) タイトルからメーカー名を付与（出力: public/autohome_ranking_with_image_urls_with_maker.csv）
          python tools/stage_add_manufacturer_from_title.py public/autohome_ranking_with_image_urls.csv
          # 3) メーカー名を日本語へ翻訳（出力: public/autohome_ranking_with_image_urls_with_maker_with_maker_ja.csv）
          python tools/stage_translate_maker_to_ja.py public/autohome_ranking_with_image_urls_with_maker.csv
          # 4) （復活）画像を実ファイルとして保存するステージ
          #    以前 .github/scripts/stage2_images_to_public.py だったものを tools に移しただけ
          python tools/stage2_images_to_public.py public/autohome_ranking_with_image_urls.csv

      # あなたの要望どおり、CSVは最終JA版のみをアップロード
      - name: Upload artifact (ranking final csv only)
        uses: actions/upload-artifact@v4
        with:
          name: autohome-ranking-csv
          path: |
            public/autohome_ranking_with_image_urls_with_maker_with_maker_ja.csv
          if-no-files-found: warn

      # 画像は別アーティファクトで。保存先は stage2 スクリプト既定の出力パスに合わせています。
      # （典型的には public/images/** または public/autohome_images/** など。既定出力に追従できるよう広めに指定）
      
      # === 新規追加: ランキングCSVから series_list.csv を生成（上位100件） ===
      - name: Build series_list.csv (top 100)
        run: |
          python - <<'PY'
          import re,csv,glob,sys
          ids=set()
          for path in glob.glob('public/*.csv'):
              with open(path, 'r', encoding='utf-8', errors='ignore') as f:
                  for line in f:
                      for m in re.finditer(r'https?://www\.autohome\.com\.cn/(\d+)', line):
                          ids.add(m.group(1))
          if not ids:
              print("No series IDs found in public/*.csv", file=sys.stderr)
          ids = sorted(ids, key=lambda x:int(x))[:100]
          with open('public/series_list.csv','w', newline='', encoding='utf-8') as f:
              w=csv.writer(f)
              w.writerow(['series_id','series_url','config_url'])
              for sid in ids:
                  series_url=f'https://www.autohome.com.cn/{sid}'
                  config_url=f'https://www.autohome.com.cn/config/series/{sid}.html#pvareaid=3454437'
                  w.writerow([sid, series_url, config_url])
          print(f'Wrote {len(ids)} rows to public/series_list.csv')
          PY

      - name: Upload artifact (series list for config)
        uses: actions/upload-artifact@v4
        with:
          name: autohome-series-list
          path: public/series_list.csv
          if-no-files-found: error
      - name: Upload artifact (ranking images)
        uses: actions/upload-artifact@v4
        with:
          name: autohome-ranking-images
          path: |
            public/**/*.jpg
            public/**/*.jpeg
            public/**/*.png
          if-no-files-found: warn
