name: Autohome Rank Enrich (brand column + tiles artifacts)

on:
  workflow_dispatch:
    inputs:
      target_month:
        description: "Target month (YYYY-MM), e.g., 2025-08"
        required: false
  schedule:
    - cron: "0 3 5 * *"   # 毎月5日 03:00 UTCに実行（任意）

jobs:
  autohome-rank-enrich:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      TARGET_MONTH: ${{ inputs.target_month }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set TARGET_MONTH if empty (fallback to previous month)
        id: setmonth
        run: |
          if [ -z "${TARGET_MONTH}" ]; then
            TARGET_MONTH=$(date -u -d "$(date +%Y-%m-15) -1 month" +%Y-%m)
            echo "TARGET_MONTH=$TARGET_MONTH" >> $GITHUB_ENV
          else
            echo "TARGET_MONTH=$TARGET_MONTH" >> $GITHUB_ENV
          fi
          echo "Using TARGET_MONTH=${TARGET_MONTH}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install openai

      # ← ここが豆腐対策（変更はこの1ステップだけ追加でした）
      - name: Install Chinese CJK fonts for headless rendering
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk fonts-wqy-zenhei fonts-wqy-microhei
          sudo fc-cache -fv

      - name: Install Playwright Chromium (if needed by existing pipeline)
        run: |
          python - <<'PY'
          import sys, subprocess
          try:
              import playwright  # noqa
              subprocess.run([sys.executable, "-m", "playwright", "install", "chromium"], check=True)
          except Exception:
              print("playwright not installed; skipping.")
          PY

      - name: Run existing VLM pipeline to produce the raw CSV
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          mkdir -p data
          python vlm_rank_reader.py \
            --from-url "https://www.autohome.com.cn/rank/1/${TARGET_MONTH}.html" \
            --fullpage-split \
            --tile-height 1200 \
            --tile-overlap 220 \
            --out "data/autohome_raw_${TARGET_MONTH}.csv"

      - name: Build tiles index (optional but useful)
        run: |
          if [ -d tiles ]; then
            {
              echo '<!doctype html><meta charset="utf-8"><title>Tiles Preview</title>'
              echo '<style>body{font-family:system-ui,sans-serif;padding:24px;background:#111;color:#eee}'
              echo '.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:12px}'
              echo 'figure{margin:0;background:#222;padding:8px;border-radius:8px}'
              echo 'figcaption{font-size:12px;margin-top:6px;color:#ccc;word-break:break-all}'
              echo 'img{max-width:100%;height:auto;display:block;border-radius:4px}'
              echo '</style><h1>Autohome tiles</h1><div class="grid">'
              for f in tiles/*.jpg tiles/*.jpeg tiles/*.png; do
                [ -e "$f" ] || continue
                bn=$(basename "$f")
                echo "<figure><img src=\"$bn\" alt=\"$bn\"><figcaption>$bn</figcaption></figure>"
              done
              echo '</div>'
            } > tiles/index.html
          else
            echo "no tiles/ directory found"
          fi

      - name: Upload tiles as artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: autohome-tiles-${{ env.TARGET_MONTH }}
          path: |
            tiles/*.jpg
            tiles/*.jpeg
            tiles/*.png
            tiles/index.html
          if-no-files-found: warn
          retention-days: 14

      - name: Enrich brand column (new CSV)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python tools/enrich_brand_llm.py \
            --in  "data/autohome_raw_${TARGET_MONTH}.csv" \
            --out "data/autohome_rank_${TARGET_MONTH}.csv" \
            --no-llm

      - name: Upload CSVs as artifact (optional)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: autohome-csvs-${{ env.TARGET_MONTH }}
          path: |
            data/autohome_raw_${{ env.TARGET_MONTH }}.csv
            data/autohome_rank_${{ env.TARGET_MONTH }}.csv
          if-no-files-found: ignore
          retention-days: 30

      - name: Commit CSVs
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "data/autohome_raw_${TARGET_MONTH}.csv" "data/autohome_rank_${TARGET_MONTH}.csv" || true
          git commit -m "autohome rank CSV (raw & brand) for ${TARGET_MONTH}" || echo "no changes"
          git push
