name: from-spec-links

on:
  workflow_dispatch:

jobs:
  from-spec-links:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # ★最小修正点：openai を確実に入れる（Playwright と一緒に）
      - name: Install deps (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install "openai>=1.40,<2" playwright
          python -m playwright install chromium
          python -c "import openai; print('✅ openai installed version:', openai.__version__)"

      - name: Download spec_links artifact
        uses: actions/download-artifact@v4
        with:
          name: spec_links
          path: .

      - name: Prepare output directory
        run: mkdir -p public/config_csv

      - name: Run autohome_config_to_csv per link (翻訳あり)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          set -eux
          test -s spec_links.jsonl
          cat spec_links.jsonl | jq -c '.[]' | while read -r line; do
            rank=$(echo "$line" | jq -r .rank)
            series_id=$(echo "$line" | jq -r .series_id)
            spec_url=$(echo "$line" | jq -r .spec_url)
            printf -v rank3 "%03d" "$rank"
            echo "::group::[${rank3}] ${series_id} -> ${spec_url}"
            python tools/autohome_config_to_csv.py --series "${series_id}"
            echo "::endgroup::"
          done

      - name: Upload config CSVs
        uses: actions/upload-artifact@v4
        with:
          name: autohome-config-csvs
          path: public/config_csv
          if-no-files-found: error
