name: Autohome Rank Enrich (brand column + tiles artifacts)

on:
  workflow_dispatch:
    inputs:
      target_month:
        description: "Target month (YYYY-MM), e.g., 2025-08"
        required: false
  schedule:
    - cron: "0 3 5 * *"

jobs:
  autohome-rank-enrich:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      TARGET_MONTH: ${{ inputs.target_month }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set TARGET_MONTH if empty
        id: setmonth
        run: |
          if [ -z "${TARGET_MONTH}" ]; then
            TARGET_MONTH=$(date -u -d "$(date +%Y-%m-15) -1 month" +%Y-%m)
            echo "TARGET_MONTH=$TARGET_MONTH" >> $GITHUB_ENV
          else
            echo "TARGET_MONTH=$TARGET_MONTH" >> $GITHUB_ENV
          fi

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install openai playwright pillow

      - name: Install Chinese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk fonts-wqy-zenhei fonts-wqy-microhei
          sudo fc-cache -fv

      - name: Install Playwright Chromium
        run: python -m playwright install chromium

      - name: Run VLM pipeline
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          mkdir -p data
          python vlm_rank_reader.py \
            --from-url "https://www.autohome.com.cn/rank/1/${TARGET_MONTH}.html" \
            --fullpage-split \
            --tile-height 1200 \
            --tile-overlap 220 \
            --out "data/autohome_rank_${TARGET_MONTH}.csv"

      - name: Upload CSVs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: autohome-csvs-${{ env.TARGET_MONTH }}
          path: data/autohome_rank_${{ env.TARGET_MONTH }}.csv
          if-no-files-found: ignore
          retention-days: 30

      - name: Commit CSVs
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "data/autohome_rank_${TARGET_MONTH}.csv" || true
          git commit -m "autohome rank CSV with brand for ${TARGET_MONTH}" || echo "no changes"
          git push
