name: Monthly append series_url & enrich brand/series (rank/1 infinite scroll + global translation)

on:
  workflow_dispatch:
  schedule:
    - cron: "15 1 2 * *" # 毎月2日 10:15 JST

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install pandas unidecode opencc-python-reimplemented playwright beautifulsoup4 requests
          playwright install chromium

      - name: Install CJK fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      - name: Resolve paths
        run: pwd && ls -R scripts || true

      - name: Append series_url from /rank/1 (Playwright infinite scroll)
        run: |
          python scripts/append_series_url.py

      - name: Enrich brand/model from <title> via LLM or rules
        run: |
          python scripts/enrich_brand_model.py

      - name: Translate brand/model to Japanese (rule-based global mapping)
        run: |
          python scripts/translate_brand_model_ja.py \
            --inp data \
            --pattern "autohome_raw_*.csv" \
            --out-suffix "_ja"

      - name: List outputs before commit
        run: ls -lh data | tail -n 20

      - name: Commit artifacts
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "auto: append + enrich + translate (global rule) [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
