name: monthly-rank-playwright

on:
  # 定期実行（必要なければ消してOK）
  schedule:
    - cron: '0 1 * * *'
  # 手動実行
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Playwright (Chromium)
        run: |
          pip install --upgrade pip
          pip install playwright
          playwright install --with-deps chromium

      - name: Run Stage0 (click-open collect)
        run: |
          mkdir -p data/rank1_click_collect
          python tools/rank1_stage0_click_open_collect.py \
            --url "https://www.autohome.com.cn/rank/1" \
            --outdir "data/rank1_click_collect" \
            --max 50 \
            --wait-ms 220 \
            --max-scrolls 220 \
            --pre-wait 1500 \
            --image-name rank_full.png

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rank1_click_open_collect_outputs
          path: |
            data/rank1_click_collect/index.csv
            data/rank1_click_collect/rank_full.png
            data/rank1_click_collect/rank_page.html
            data/rank1_click_collect/series_html/
          if-no-files-found: error
