name: Stage0 Click→Open→Collect (Autohome series URLs)

on:
  workflow_dispatch:
  schedule:
    - cron: "15 1 2 * *"  # 毎月2日 01:15 UTC

jobs:
  run:
    name: Run Stage0 (click & collect series URLs)
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install playwright==1.*
          python -m playwright install --with-deps chromium

      - name: Click open & collect series URLs
        run: |
          python tools/rank1_stage0_click_open_collect.py \
            --url "https://www.autohome.com.cn/beijing/sales/2025-09" \
            --outdir data/rank1_click \
            --max 100 \
            --wait-ms 220 \
            --max-scrolls 240 \
            --pre-wait 1200

      - name: Show CSV (head)
        run: |
          echo "--- series_urls.csv ---"
          head -n 20 data/rank1_click/series_urls.csv || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rank1_click_series_urls
          path: data/rank1_click/series_urls.csv
          if-no-files-found: error
