name: stage0_fullimage_and_links

on:
  workflow_dispatch:
  schedule:
    - cron: "15 1 2 * *"  # monthly at 01:15 UTC on the 2nd

jobs:
  stage0_fullimage_and_links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # CJK fonts to avoid tofu/garbled text in screenshots
      - name: Install CJK fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            fonts-noto-cjk fonts-noto-cjk-extra \
            fonts-wqy-zenhei fonts-wqy-microhei \
            fonts-noto-color-emoji
          fc-cache -f -v

      - name: Install Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          python -m playwright install chromium

      - name: Run Stage0 (full image + network link capture)
        run: |
          mkdir -p data/rank1_full
          python tools/rank1_stage0_fullimage_and_links.py \
            --url "https://www.autohome.com.cn/rank/1" \
            --outdir "data/rank1_full" \
            --pre-wait 1500 \
            --wait-ms 300 \
            --max-scrolls 220 \
            --image-name "rank_full.png"

      - name: Upload full image
        uses: actions/upload-artifact@v4
        with:
          name: rank1_full_image
          path: data/rank1_full/rank_full.png

      - name: Upload series links (index.csv)
        uses: actions/upload-artifact@v4
        with:
          name: rank1_series_links
          path: data/rank1_full/index.csv

      - name: Upload captured JSON (debug)
        uses: actions/upload-artifact@v4
        with:
          name: rank1_captured_json
          path: data/rank1_full/captured_json

      - name: Upload page HTML snapshot
        uses: actions/upload-artifact@v4
        with:
          name: rank1_page_html
          path: data/rank1_full/page.html
