name: stage0_fullpage_capture

on:
  workflow_dispatch:
  schedule:
    - cron: "15 1 2 * *"   # 毎月2日 01:15 UTC（北京09:15）

jobs:
  capture_fullpage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Playwright + fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            fonts-noto-cjk fonts-noto-cjk-extra \
            fonts-wqy-zenhei fonts-wqy-microhei \
            fonts-noto-color-emoji
          python -m pip install -U pip
          pip install playwright
          python -m playwright install chromium

      - name: Capture full page screenshots
        run: |
          mkdir -p captures
          python .github/scripts/stage0_fullpage_capture.py
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fullpage-screenshots
          path: captures/**/*.png
