name: Monthly Autohome Rank (Playwright)

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'Autohome ranking URL (e.g. https://www.autohome.com.cn/beijing/sales/2025-10)'
        required: true
        default: 'https://www.autohome.com.cn/beijing/sales/2025-09'
      top_n:
        description: 'How many ranks to collect'
        required: true
        default: '100'
  schedule:
    - cron: '15 1 2 * *' # 毎月2日 01:15 UTC

jobs:
  stage0_click_collect:
    name: Stage0 Click→Open→Collect
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Playwright + Chromium
        run: |
          python -m pip install --upgrade pip
          pip install playwright==1.*
          python -m playwright install --with-deps chromium

      - name: Collect series URLs by clicking (ranking order)
        run: |
          URL="${{ github.event.inputs.target_url }}"
          TOPN="${{ github.event.inputs.top_n }}"
          if [ -z "$URL" ]; then URL="https://www.autohome.com.cn/beijing/sales/2025-09"; fi
          if [ -z "$TOPN" ]; then TOPN="100"; fi

          python tools/rank1_stage0_click_open_collect.py \
            --url "$URL" \
            --outdir data/rank1_click \
            --max "$TOPN" \
            --wait-ms 220 \
            --max-scrolls 240 \
            --pre-wait 1200

      - name: Show CSV (head)
        run: |
          echo "--- data/rank1_click/series_urls.csv ---"
          sed -n '1,20p' data/rank1_click/series_urls.csv || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rank1_click_series_urls
          path: data/rank1_click/series_urls.csv
          if-no-files-found: error
