name: Monthly VLM Rank Capture

on:
  workflow_dispatch:
    inputs:
      url:
        description: "ランキングページURL"
        required: true
        default: "https://www.autohome.com.cn/rank/1-3-1071-x/2025-08.html"
  schedule:
    - cron: "0 6 10 * *"   # 毎月10日 06:00(UTC) = 北京時間14:00

jobs:
  capture:
    runs-on: ubuntu-latest
    timeout-minutes: 35
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      # 失敗時に最大3回リトライ
      - name: Run vlm_rank_reader.py (retry x3)
        shell: bash
        run: |
          set -e
          URL="${{ github.event.inputs.url || 'https://www.autohome.com.cn/rank/1-3-1071-x/2025-08.html' }}"
          for i in 1 2 3; do
            echo "Attempt $i/3 ..."
            if python vlm_rank_reader.py \
              --from-url "$URL" \
              --fullpage-split \
              --tile-height 1200 \
              --tile-overlap 240 \
              --provider openai \
              --model gpt-4o \
              --openai-api-key "${{ secrets.OPENAI_API_KEY }}" \
              --max-side 1800 \
              --jpeg-quality 82 \
              --csv result.csv ; then
              break
            fi
            if [ $i -lt 3 ]; then
              echo "Retrying in 12s..."; sleep 12
            else
              echo "All attempts failed"; exit 1
            fi
          done

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: autohome-rank-csv
          path: result.csv
          retention-days: 30

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: autohome-rank-tiles
          path: tiles/
          if-no-files-found: ignore
          retention-days: 7
