name: Monthly VLM Rank Capture

on:
  workflow_dispatch:
    inputs:
      url:
        description: "ランキングページURL"
        required: true
        default: "https://www.autohome.com.cn/rank/1-3-1071-x/2025-08.html"
  schedule:
    - cron: "0 6 10 * *"   # 毎月10日 06:00 UTC (北京時間14:00)

jobs:
  capture:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run vlm_rank_reader.py
        run: |
          URL="${{ github.event.inputs.url || 'https://www.autohome.com.cn/rank/1-3-1071-x/2025-08.html' }}"
          python vlm_rank_reader.py \
            --from-url "$URL" \
            --fullpage-split \
            --tile-height 1200 \
            --provider openai \
            --model gpt-4o \
            --openai-api-key "${{ secrets.OPENAI_API_KEY }}" \
            --max-side 1600 \
            --jpeg-quality 80 \
            --csv result.csv

      - uses: actions/upload-artifact@v4
        with:
          name: autohome-rank-csv
          path: result.csv
          retention-days: 30

      - uses: actions/upload-artifact@v4
        with:
          name: autohome-rank-tiles
          path: tiles/
          if-no-files-found: ignore
          retention-days: 7
